### ISSUE TITLE
init() does not check results

### ISSUE THREAD

**Issue by MauiJerry** [Seeed-Studio/Grove_Digital_Light_Sensor#1]
The Digital Light Sensor may not properly initialize on some arduino systems.  The current init function does not check status of the initialization tools.   This was noted recently on the Intel Edison Arduino boards.

**Comment by KillingJacky** [comment]
Sorry guy, we just somehow didn't see your issue. --!! If I may, I want to be indicated that have you resolved this issue? If you have, we need not to reinvent the wheel then.

**Comment by MauiJerry** [comment]
oi… this was a while back… like 10,000 projects ago ;-)
I’ll have to check the notes and get back to ya.

Jerry Isdale
isdale@gmail.com

Design Global, Build Local.

Opinions herein are mine and may not reflect those of other makers, hackers or humans in general. Please do not destroy Earth because of them.

**Comment by ackPeng** [comment]
@MauiJerry  Do you still have this question now?

**Comment by MauiJerry** [comment]
so long ago i have lost context completely. sorry. might as well close the
issue,
- jerry isdale
Maui Institute of Art and Technology

sent from my phone, sorry for any voice2text goofs

**Comment by ackPeng** [comment]
OK, I will close this issue. If you have any questions, please feel free to contact me. Thank you.
