### ISSUE TITLE
Data discontinuity 

### ISSUE THREAD

**Issue by KHadef** [Seeed-Studio/Grove_Digital_Light_Sensor#3]
First thank you for the library.

I am conducting a simple experiment. I have an LED that changes it's intensity slowly and continuously. I am using the visible mode and I want to plot a graph of lux value vs. the change in LED intensity. 
I am having a trouble with lux readings, they are discrete, for example the reading stays at 0 for some time then suddenly jump to 14, and so on. What I want is a continuous change in lux.

Is the problem due to the sensor sensitivity or due to something in the library that could be changed? 
Is it possible to modify the library in order to be able to read lux values in decimals or more continuous manner? Would you please do that for us if possible? Thank you.

**Comment by ackPeng** [comment]
@KHadef  This is indeed discrete, and this may be the current real data. Sensors often have these jump conditions. Perhaps some filtering algorithms can be used to eliminate this data. Do you have any questions about this?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
